spring.application.name=gym-booking-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5434/gym_booking_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/gym-system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
