
events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /api/ {
            proxy_pass http://gym-booking-service:8082/api/;

            # Headers estandar para que el microservicio sepa la info real del cliente original
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Importante: reenviamos el header Authorization tal cual llega,
            # sin modificarlo, para que el microservicio pueda validar el JWT
            proxy_pass_header Authorization;
        }
    }
}
